plugin:
    name: 'Otimizar imagens uploads'
    description: 'Otimizar uploads das fotos no backend interno.'
    author: Diveramkt
    icon: oc-icon-upload
    homepage: ''
permissions:
    Uploads.manage_upload:
        tab: 'diveramkt.uploads::lang.plugin.name'
        label: 'Gerenciar Uploads imagens'
    Uploads.delete_media:
        tab: 'diveramkt.uploads::lang.plugin.name'
        label: 'Deletar imagens em Mídias'
    Uploads.readOnly_media:
        tab: 'diveramkt.uploads::lang.plugin.name'
        label: 'Apenas acessar as imagens em Mídias'